# Stage 1: Building the React application
FROM node
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the source code of the app into the container
COPY src/ src/
COPY public/ public/

# Build the application
RUN npm run build

# Expose port 80 for the web server
EXPOSE 3000

CMD ["npm", "start"]